config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :allblogs do
    resources :comments
  end

end

app/models/allblog.rb
class Allblog < ActiveRecord::Base
    has_many :comments, :foreign_key => "blog_id"
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :allblog
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :allblogs
end

app/controllers/allblogs_controller.rb
class AllblogsController < ApplicationController

    def index
        @allblogs = Allblog.all
    end
    
    def show
        @allblog = Allblog.find(params[:id])
        @comment = Comment.new
        @comment.blog_id = @allblog.id
        @comments = Comment.where("blog_id = '#{@allblog.id}'")
    end
    
    def new
        @allblog = Allblog.new
    end

    def edit
        @allblog = Allblog.find(params[:id])
    end

    def update
        @allblog = Allblog.find(params[:id])
        if @allblog.update_attributes(allblog_param)
            redirect_to :action => 'show', :id => @allblog
        else
            @allblogs = Allblog.all
            render :action => 'edit'
        end
    end
    
    def create
        @allblog  = Allblog.new(allblog_param)
        
        if @allblog.save
            redirect_to :action => 'index'
        else
            @allblogs = Allblog.all
            render :action => 'new'
        end
    end

    def destroy
        @allblog = Allblog.find(params[:id]).destroy
        redirect_to :action => 'index'
    end

    def allblog_params
        params.require(:allblogs).permit(:user_id, :headline, :text, :description, :imagepath)
    end


    def allblog_param
        params.require(:allblog).permit(:user_id, :headline, :text, :description, :imagepath)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment  = Comment.new(cmnt_param)

        if @comment.save!
            redirect_to :back
        else
            @comments = Comment.all
            render :action => 'allblogs/show'
        end
    end

    def delete
        @comment = Comment.find(params[:id]).destroy
        redirect_to :action => 'allblogs/show'
    end

    def cmnt_param
        params.require(:comment).permit(:blog_id, :comment)
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/allblog_helper.rb
module AllblogHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/allblogs/_comment.html.erb
<div>
<p> <%= comment.comment %> </p>
</div>

app/views/allblogs/edit.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>
<h2>Create New Blog</h2>

<%= form_for @allblog, :url =>{:action => "update", :id => @allblog} do |form| %>
    <div class="container">
        <div class="form-group">
            <label>Headline</label>
            <%= form.text_field "headline" %>
        </div>

        <div class="form-group">
            <label>Brief</label>
            <%= form.text_field "text" %>
        </div>

        <div class="form-group">
            <label>Description</label>
            <%= form.cktext_area "description", ckeditor: { language: 'en'} %>
        </div>
        <%= submit_tag "Save Changes" %>
    </div>
<% end %>

app/views/allblogs/index.html.erb
<% if @allblogs.blank? %>
<h1>Create your first <%= link_to "blog", {:action => 'new'} %></h1>
<% else %>
<h1>Your created blogs:</h1>
<hr>

<div class="container">
    <ul id = "allblogs" class="list-group">
        <% @allblogs.each do |c| %>
            <li class="list-group-item well"><%= link_to c.headline, {:action => 'show', :id => c.id} -%>
            <hr><p><b><%= link_to "Edit", {:action => 'edit', :id => c.id } -%></b>
            <b><%= link_to "Delete", allblog_path(:id =>c.id), :method => 'delete' %></b></p></li>
        <% end %>
        
    </ul>

    <h3><%= link_to "Create new Blog", {:action => 'new' }%></h3>
</div>


<% end %>

app/views/allblogs/new.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>
<h2>Create New Blog</h2>

<%= form_for @allblog, :url =>{:action => "create", :id => @allblog} do |form| %>
    <div class="container">
        <div class="form-group">
            <label>Headline</label>
            <%= form.text_field :headline %>
        </div>

        <div class="form-group">
            <label>Brief</label>
            <%= form.text_field :text %>
        </div>

        <div class="form-group">
            <label>Description</label>
            <%= form.cktext_area :description, ckeditor: { language: 'en'} %>
        </div>
        <%= submit_tag "Create" %>
    </div>
<% end %>

app/views/allblogs/show.html.erb
<div class="container">
    <div class="well">
        <h1><%= @allblog.headline %></h1>
        <p><%=raw @allblog.description %></p>
    <div>

    <div>
        <h2>Comments</h2>
        <% @comments.each do |c| %>
            <p><%= c.comment %></p>
        <% end %>
    </div>
</div>
<hr>
<br>
<div class="container">
<%= render partial: 'comments/form' %>
</div>
<%= link_to 'Back', {:action => 'index'} %>

app/views/comments/_form.html.erb
<h2>Post a comment</h2>

<%= form_for [ @allblog, @comment ] do |f| %>
    <p>
    <%= f.label :Comment %><br/>
    <%= f.text_field :comment %>
    <%= f.hidden_field :blog_id, :value => @allblog.id%>
    </p>
    
    <%= f.submit 'Submit' %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>